name: Code Checks
on:
  pull_request:
    branches: ["main", "production"]
  workflow_dispatch:
concurrency:
  group: code-check-${{ github.event.pull_request.head.ref || github.ref_name }}
  cancel-in-progress: true
jobs:
  lint:
    name: Code Linting
    runs-on: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name != github.repository && 'ubuntu-latest' || fromJSON('["self-hosted","Linux","X64"]') }}
    steps:
      - uses: actions/checkout@v7
      - name: Set up Golang
        uses: actions/setup-go@v7
        with:
          go-version: "1.26.5"
      - name: Lint Code
        uses: golangci/golangci-lint-action@v9
        with:
          version: "latest"
          args: "--config=default.golangci.yml"
  build:
    name: Build Binary
    runs-on: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name != github.repository && 'ubuntu-latest' || fromJSON('["self-hosted","Linux","X64"]') }}
    steps:
      - uses: actions/checkout@v7
      - name: Set up Golang
        uses: actions/setup-go@v7
        with:
          go-version: "1.26.5"
      - name: Build Binary
        run: go build -o main .
