name: Code Checks
on:
  push:
    branches-ignore: ["main", "production"]
  pull_request:
    branches: ["main", "production"]
    types:
      - closed
  workflow_dispatch:
jobs:
  lint:
    name: Code Linting
    runs-on: ["self-hosted", "X64"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Golang
        uses: actions/setup-go@v5
        with:
          go-version: ">=1.24"
          cache: 'false'
      - name: Lint Code
        uses: golangci/golangci-lint-action@v7
        with:
          version: "latest"
          args: "--config=default.golangci.yml"
  build:
    name: Build Binary
    needs: [lint]
    runs-on: ["self-hosted", "X64"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Golang
        uses: actions/setup-go@v5
        with:
          go-version: ">=1.24"
          cache: 'false'
      - name: Build Binary
        run: go build -o hyuabot-kakao-backend-go ./...
